/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PenampilGambarButton;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;



/**
 *
 * @author Asus
 */
public class Button extends javax.swing.JFrame {

    /**
     * Creates new form Button
     */
    public Button() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        buttonGunung = new javax.swing.JButton();
        buttonPantai = new javax.swing.JButton();
        buttonPerdesaan = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        labelGunung = new javax.swing.JLabel();
        labelPantai = new javax.swing.JLabel();
        labelPerdesaan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        buttonGunung.setText("Gunung");
        buttonGunung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGunungActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonGunung);

        buttonPantai.setText("Pantai");
        buttonPantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPantaiActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonPantai);

        buttonPerdesaan.setText("Perdesaan");
        buttonPerdesaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerdesaanActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonPerdesaan);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        buttonPanel.add(buttonExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        labelGunung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PenampilGambarButton/Gunung.jpeg"))); // NOI18N
        imagePanel.add(labelGunung, "0");

        labelPantai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PenampilGambarButton/Pantai.jpeg"))); // NOI18N
        imagePanel.add(labelPantai, "1");

        labelPerdesaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PenampilGambarButton/Perdesaan.jpeg"))); // NOI18N
        imagePanel.add(labelPerdesaan, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGunungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGunungActionPerformed
        CardLayout cl =(CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_buttonGunungActionPerformed

    private void buttonPantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPantaiActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_buttonPantaiActionPerformed

    private void buttonPerdesaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerdesaanActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_buttonPerdesaanActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Button fullFrame = new Button();
                
                GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonGunung;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton buttonPantai;
    private javax.swing.JButton buttonPerdesaan;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel labelGunung;
    private javax.swing.JLabel labelPantai;
    private javax.swing.JLabel labelPerdesaan;
    // End of variables declaration//GEN-END:variables
}
