/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PenampilGambarComboBox;

import java.awt.CardLayout;

/**
 *
 * @author Asus
 */
public class ComboBox extends javax.swing.JFrame {

    /**
     * Creates new form ComboBox
     */
    public ComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPilih = new javax.swing.JComboBox<>();
        imgPanel = new javax.swing.JPanel();
        labelGunung = new javax.swing.JLabel();
        labelPantai = new javax.swing.JLabel();
        labelPerdesaan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pilih Gambar :");
        pilihan.add(jLabel1);

        cbPilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gunung", "Pantai", "Perdesaan" }));
        cbPilih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPilihItemStateChanged(evt);
            }
        });
        pilihan.add(cbPilih);

        getContentPane().add(pilihan, java.awt.BorderLayout.PAGE_START);

        imgPanel.setLayout(new java.awt.CardLayout());

        labelGunung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Gunung.jpeg"))); // NOI18N
        imgPanel.add(labelGunung, "0");

        labelPantai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pantai.jpeg"))); // NOI18N
        imgPanel.add(labelPantai, "1");

        labelPerdesaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Perdesaan.jpeg"))); // NOI18N
        imgPanel.add(labelPerdesaan, "2");

        getContentPane().add(imgPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPilihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPilihItemStateChanged
        CardLayout cl = (CardLayout)(imgPanel.getLayout());
        cl.show(imgPanel, String.valueOf(cbPilih.getSelectedIndex()));
    }//GEN-LAST:event_cbPilihItemStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPilih;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelGunung;
    private javax.swing.JLabel labelPantai;
    private javax.swing.JLabel labelPerdesaan;
    private javax.swing.JPanel pilihan;
    // End of variables declaration//GEN-END:variables
}
